- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install mongodb"
  become: yes
  apt:
    name: ["mongodb"]
    state: latest
    update_cache: yes

- name: "Bind ip to mongodb"
  template:
    src: db_dns.txt
    dest: /home/ubuntu/db_dns.txt
  shell:
    echo $db_dns.txt